[internal]
exten => 6001,1,Dial(PJSIP/6001,20)
same => n,VoiceMail(6001@default,u)
same => n,Hangup()

exten => 6002,1,Dial(PJSIP/6002,20)
same => n,VoiceMail(6002@default,u)
same => n,Hangup()

exten => 6003,1,Dial(PJSIP/6003,20)
same => n,VoiceMail(6003@default,u)
same => n,Hangup()
